USE DATABASE AIRLINE_DW;
USE SCHEMA BASE;

CREATE TABLE ORDER_RAW
(
    RAW_RECORD          VARIANT,
    FILE_NAME           STRING,
    FILE_ROW_NUMBER     NUMBER,
    SOURCE_SYSTEM       STRING,
    LOAD_BATCH_ID       STRING,
    LOAD_TIMESTAMP      TIMESTAMP_NTZ,
    FILE_RECEIVED_DATE  DATE,
    RECORD_HASH         STRING
);

CREATE TABLE CUSTOMER_RAW
(
    RAW_RECORD          VARIANT,
    FILE_NAME           STRING,
    FILE_ROW_NUMBER     NUMBER,
    SOURCE_SYSTEM       STRING,
    LOAD_BATCH_ID       STRING,
    LOAD_TIMESTAMP      TIMESTAMP_NTZ,
    FILE_RECEIVED_DATE  DATE,
    RECORD_HASH         STRING
);


CREATE TABLE ORDER_HEADER_RAW
(
    RAW_RECORD          VARIANT,
    FILE_NAME           STRING,
    FILE_ROW_NUMBER     NUMBER,
    SOURCE_SYSTEM       STRING,
    LOAD_BATCH_ID       STRING,
    LOAD_TIMESTAMP      TIMESTAMP_NTZ,
    FILE_RECEIVED_DATE  DATE,
    RECORD_HASH         STRING
);