USE DATABASE AIRLINE_DW;

CREATE SCHEMA IF NOT EXISTS LANDING;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS BASE;

CREATE SCHEMA IF NOT EXISTS MART;

CREATE SCHEMA IF NOT EXISTS AUDIT;