USE DATABASE AIRLINE_DW;

USE SCHEMA BASE;

-CREATE TABLE BASE_CUSTOMER
(
    CUSTOMER_SK                 NUMBER AUTO_INCREMENT,
    CUSTOMER_ID                 STRING,
    CUSTOMER_NAME               STRING,
    EMAIL                       STRING,
    COUNTRY_CODE                STRING,
    SOURCE_SYSTEM               STRING,
    LOAD_BATCH_ID               STRING,
    CREATED_TIMESTAMP           TIMESTAMP,
    UPDATED_TIMESTAMP           TIMESTAMP,
    RECORD_HASH                STRING,
    IS_CURRENT                 BOOLEAN,
    IS_DELETED                 BOOLEAN
);

CREATE TABLE BASE_ORDERS
(
ORDER_SK            NUMBER AUTO_INCREMENT,
ORDER_ID            STRING,
CUSTOMER_SK         STRING,
ORDER_DATE          DATE,
ORDER_STATUS        STRING,
TOTAL_AMOUNT        DECIMAL(2,0),
SOURCE_SYSTEM       STRING,
LOAD_BATCH_ID       STRING,
CREATED_TIMESTAMP   TIMESTAMP_NTZ,
UPDATED_TIMESTAMP   TIMESTAMP,
RECORD_HASH         STRING,
IS_CURRENT          BOOLEAN,
IS_DELETED          BOOLEAN
);

CREATE TABLE BASE_SETTLEMENT
(
SETTLEMENT_SK            NUMBER AUTO_INCREMENT,
SETTLEMENT_ID            STRING,
ORDER_SK                 STRING,
SETTLEMENT_DATE          DATE,
SETTLEMENT_STATUS        STRING,
SETTLEMENT_AMOUNT        DECIMAL(2,0),
SOURCE_SYSTEM            STRING,
LOAD_BATCH_ID            STRING,
CREATED_TIMESTAMP        TIMESTAMP_NTZ,
UPDATED_TIMESTAMP        TIMESTAMP,
RECORD_HASH              STRING,
IS_CURRENT                BOOLEAN,
IS_DELETED                BOOLEAN
);